dist: xenial

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt.bell-sw.com/ stable main'
      key_url: 'https://download.bell-sw.com/pki/GPG-KEY-bellsoft'
    packages:
      - bellsoft-java8-full

git:
  depth: 3

branches:
  only: 
    - master

env:
  - GRADLE_OPTS="-Xmx4096m"

before_cache:
  - rm -f  $HOME/.mcreator/gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.mcreator/gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.mcreator/gradle/caches/minecraft/deobfedDeps/providedDummy.jar
  - rm -f  $HOME/.mcreator/gradle/caches/minecraft/deobfedDeps/compileDummy.jar
cache:
  directories:
    - $HOME/.mcreator/gradle/caches/
    - $HOME/.mcreator/gradle/wrapper/

language: java

script:
  - chmod +x gradlew
  - xvfb-run ./gradlew test
