dist: trusty

git:
  depth: 3

branches:
  only:
    - master

env:
  - GRADLE_OPTS="-Xmx6000m"

before_cache:
  - rm -f  $HOME/.mcreator/gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.mcreator/gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.mcreator/gradle/caches/minecraft/deobfedDeps/providedDummy.jar
  - rm -f  $HOME/.mcreator/gradle/caches/minecraft/deobfedDeps/compileDummy.jar
cache:
  directories:
    - $HOME/.mcreator/gradle/caches/
    - $HOME/.mcreator/gradle/wrapper/

language: java
jdk: oraclejdk8
 addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  # Make gradle executable
  - chmod +x gradlew

  # Output time every 5 minutes or Travis kills the job (if decompile takes too long)
  - while sleep 5m; do echo "=====[ $SECONDS seconds still running ]====="; done &

  # Run unit tests
  - xvfb-run ./gradlew test
  
  # Kill background sleep loop
  - kill %1
