blank_issues_enabled: false
contact_links:
  - name: [Read before opening a new issue] Issue tracker rules and tips
    url: https://mcreator.net/wiki/tips-reporting-bugs-and-issues
    about: Some issue tracker rules and general tips
  - name: Knowledge base
    url: https://mcreator.net/support/knowledgebase
    about: Collection of commonly asked questions and problems
  - name: MCreator's forum
    url: https://mcreator.net/forum
    about: Alternative place to report bugs or feature requests, also place for support questions
