name: Crowdin Pull

on:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch: {}

jobs:
  crowdin-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crowdin/github-action@cb33a030bb1675169b76617d5805242aeea6eaec
        name: Pull Crowdin translations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        with:
          config: crowdin.yml
          crowdin_branch_name: master
          upload_sources: false
          upload_translations: false
          download_translations: true
          github_user_name: "github-actions"
          github_user_email: "<>"
          commit_message: "New Crowdin translations"
          localization_branch_name: localization
          pull_request_base_branch_name: master
          create_pull_request: true
          pull_request_title: "New Crowdin translations"
          pull_request_body: "New Crowdin translations"
