name: Generate documentation

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout Repository
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21.0.8+9.0.LTS'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Generate Javadoc
        run: gradle javadoc
      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@65b5dfd4f5bcd3a7403bbc2959c144256167464e
        with:
          branch: javadoc
          clean: true
          folder: build/docs/javadoc
          target-folder: .
          git-config-name: "github-actions"
          git-config-email: "<>"
