name: Build and test

permissions:
  checks: write

on:
  push:
    branches:
      - master
      - "feature/*"
      - "dev/*"
  pull_request:
    branches:
      - master
      - "feature/*"
      - "dev/*"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21.0.8+9.0.LTS'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Cache Gradle Packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.mcreator/gradle/caches/
            ~/.mcreator/gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build and Test Using Gradle
        run: xvfb-run -a gradle --no-build-cache clean test
      - name: Test Javadoc Generation
        run: ./gradlew javadoc
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@9379f0ccddcab154835d4e2487555ee79614fe95
        if: always() # always run even if the previous step fails
        with:
          include_passed: true
          detailed_summary: true
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Prepare Gradle Cache
        run: |
          rm -f  ~/.mcreator/gradle/caches/modules-2/modules-2.lock
          rm -fr ~/.mcreator/gradle/caches/*/plugin-resolution/
          rm -f  ~/.mcreator/gradle/caches/minecraft/deobfedDeps/providedDummy.jar
          rm -f  ~/.mcreator/gradle/caches/minecraft/deobfedDeps/compileDummy.jar
          rm -f  ~/.gradle/caches/modules-2/modules-2.lock
          rm -f  ~/.gradle/caches/modules-2/gc.properties
